### ISSUE TITLE
Documentation - Omitted !

### ISSUE THREAD

**Issue by atunjeafolabi** [tenancy/docs#163]
https://tenancy.dev/docs/tenancy/1.x/hooks-hostname#hook

```
public function handle(Event $event): void
    {
        if($this->hasValidDomains($event->tenant)){
        Mail::to($event->tenant->email)->send(new DomainsNotValid($event->tenant->getHostnames()));
        }
    }
```
 Exclamation mark was omitted in the _if_ condition above.

It should be : `if(!$this->hasValidDomains($event->tenant))`

According to the documentation:
"If the tenant **does not have valid domains**, we will send an email to the administrator regarding the domains not being valid."

**Comment by Plytas** [comment]
Good catch! Docs are open source so PR's are appreciated ;)

**Comment by ArlonAntonius** [comment]
Closing this as it was fixed with the PR I just merged
