### ISSUE TITLE
Suggested version should be a global js var

### ISSUE THREAD

**Issue by luceos** [tenancy/docs#34]
Currently both layout and home vue components rely on hard-coded versions to "get started" with. This value should be identified from php from the logic that caches packages, versions so that inside the loop a new cache key is created permanently that holds just the package slug and version slug of the suggested version. We can then assign the value to Javascript from inside the frontend controller.

**Comment by fletch3555** [comment]
CTA links now point at a "latest" endpoint instead of a specific version.
