### ISSUE TITLE
New lines in code blocks

### ISSUE THREAD

**Issue by fletch3555** [tenancy/docs#37]
Mentioned this in discord, but wanted to track it here as well.

Not sure if this is a docs issue or a site/CSS issue, but code blocks aren't rendering with new-lines.  All code is appearing as if it were written on a single line.  Looking at the markdown source, this is clearly not intended.

**Comment by luceos** [comment]
This was partially fix, the issue now is that code blocks aren't indented..

@paulotra https://github.com/tenancy/laravel-tenancy.com/pull/22
